# Generated by Django 3.0.6 on 2020-06-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaGuichoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='talla',
            field=models.CharField(max_length=15),
        ),
    ]
