# Generated by Django 3.0.6 on 2020-06-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaGuichoApp', '0002_auto_20200609_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calzado',
            name='talla',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='talla',
            field=models.FloatField(),
        ),
    ]
