# Generated by Django 3.0.6 on 2020-06-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaGuichoApp', '0003_auto_20200617_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='talla',
            field=models.CharField(choices=[('XS', 'ExtraSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'ExtraLarge')], max_length=2),
        ),
    ]
